# Generated by Django 5.2.1 on 2025-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
