# Generated by Django 5.2.1 on 2025-05-26 04:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
