# Generated by Django 5.2.1 on 2025-05-26 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_configuration1',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='practice.product_item1'),
        ),
        migrations.AlterField(
            model_name='product_configuration1',
            name='variationoption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='practice.variation_option1'),
        ),
        migrations.AlterField(
            model_name='product_item1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_items', to='practice.products1'),
        ),
        migrations.AlterField(
            model_name='products1',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='practice.categories1'),
        ),
        migrations.AlterField(
            model_name='variation1',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='practice.categories1'),
        ),
        migrations.AlterField(
            model_name='variation_option1',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='practice.variation1'),
        ),
    ]
