# Generated by Django 5.2.1 on 2025-05-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_phone_number'),
        ('practice', '0002_alter_product_configuration1_product_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item1',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='product_item1',
            name='cp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product_item1',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products1',
            name='decription',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to='practice.shoppingcart')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='practice.product_item1')),
            ],
        ),
    ]
