# Generated by Django 5.2.1 on 2025-05-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_phone_number'),
        ('practice', '0003_rename_price_product_item1_selling_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.product_item1')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.order')),
            ],
        ),
    ]
