# Generated by Django 5.2.1 on 2025-05-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_accountdeposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories1',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Variation1',
            new_name='Variation',
        ),
        migrations.RenameModel(
            old_name='Variation_option1',
            new_name='Variation_option',
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.order'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitems',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to='catalog.shoppingcart'),
        ),
        migrations.RenameModel(
            old_name='Product_Configuration1',
            new_name='Product_Configuration',
        ),
        migrations.RenameModel(
            old_name='Products1',
            new_name='Products',
        ),
        migrations.CreateModel(
            name='Product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('qty_in_stock', models.IntegerField()),
                ('product_img', models.ImageField(blank=True, upload_to='items/')),
                ('cp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_items', to='catalog.products')),
            ],
        ),
        migrations.AlterField(
            model_name='order_items',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product_item'),
        ),
        migrations.AlterField(
            model_name='product_configuration',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='catalog.product_item'),
        ),
        migrations.AlterField(
            model_name='shoppingcartitems',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product_item'),
        ),
        migrations.DeleteModel(
            name='Product_item1',
        ),
    ]
