# Generated by Django 5.2.1 on 2025-05-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_remove_products_category_products_catalog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catalog',
        ),
        migrations.AddField(
            model_name='gendercategory',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products'),
        ),
        migrations.DeleteModel(
            name='catalog',
        ),
    ]
