# Generated by Django 5.2.1 on 2025-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_products_catalog_gendercategory_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendercategory',
            name='catelog',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
