# Generated by Django 5.2.1 on 2025-05-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_gendercategory_catelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gendercategory',
            name='catelog',
        ),
        migrations.RemoveField(
            model_name='gendercategory',
            name='product_id',
        ),
        migrations.CreateModel(
            name='Catelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorytype_name', models.CharField(max_length=255)),
                ('catelog_name', models.CharField(max_length=225, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
    ]
